config/routes.rb
Rails.application.routes.draw do
  get 'decks/:id/download' => 'decks#download'

  resources :decks

end

app/models/card.rb
class Card < ActiveRecord::Base
	has_and_belongs_to_many :decks
end

app/models/cards_decks.rb
class CardsDecks < ActiveRecord::Base
	belongs_to:card
	belongs_to:deck
end

app/models/deck.rb
class Deck < ActiveRecord::Base
	has_and_belongs_to_many :cards
	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy, :download]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)
    rows = params[:deck][:ydk].read
    rows.each_line do |line|
      line = line.strip
      line = line.to_i
      unless line == 0
        card = Card.find(line)
        @deck.cards << card
      end
    end

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download
    filename = @deck.name + ".ydk"
    path = './tmp/deck'
    file = File.join(path, filename)
    io = File.open(file,"w")
    @deck.cards.each do |line|
      io.puts line.id
    end
    io.close
    send_file file
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_form.html.erb
<%= form_for(@deck,multipart: true) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4>デッキの名前を入力してね</h4>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <h4>デッキデータ（〜.ydk）ファイルを選択してね</h4>
    <%= f.file_field :ydk %>
  </div>
  <div class="actions">
    <%= f.submit "デッキ作成" ,:class => "btn btn-primary"%>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>Listing decks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
    <a href="/decks/<%= deck.id%>">
      <h1><%= deck.name%></h1>
    </a>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="contanir">
	<div class="row">
		<div class="col-md-12 center">
			<h1><%= @deck.name %></h1>
		</div>
	</div>
	<div class="col-md-5">
		<% @deck.cards.each do |card| %>
		<img class="thumb" card-id="<%= card.id%>" src="http://133.242.18.124/thumbnail/<%= card.id%>.jpg" />
		<% end %>
	</div>
	<!-- //right -->
	<div class="col-md-6">
		<div class="col-md-6">
			<img class="pics" />
		</div>
		<% @deck.cards.each do |card| %>
		<div class="col-md-6 <%= card.id %> desc" style="display:none;">
			<p><%= card.name %></p>
			<span><%= card.desc%></span>
		</div>
		<% end%>
	</div>
	<div class="row">
		<a href="/decks/<%= @deck.id%>/download" type="button" class="col-md-12 btn btn-primary btn-lg">デッキをダウンロード</button>
			<%= link_to 'Edit', edit_deck_path(@deck) %> |
			<%= link_to 'Back', decks_path %>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeckHub</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>